homeassistant:
  name: Home
  latitude: 45.493400
  longitude: 11.106900
  elevation: 430
  unit_system: metric
  time_zone: Europe/Rome
  #customize: !include_dir_merge_named customizations
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /media/photo

config:

frontend:

http:
  api_password: !secret http_password
  use_x_forwarded_for: true
  base_url: !secret base_url

updater:

discovery:

history:

recorder:
  purge_interval: 1
  purge_keep_days: 2

logbook:

sun:

#mqtt:
#  broker: 127.0.0.1
#  port: 1883
#  client_id: home-assistant-1
#  keepalive: 60
#  username: pi
#  password: !secret mqtt_password
#  protocol: 3.1

zwave:
  usb_path: /dev/zwave
  network_key: !secret zwave_network_key
  #config_path: /home/hass/lib/lib/python3.5/site-packages/libopenzwave-0.3.1-py3.5-linux-x86_64.egg/config
  #device_config: !include zwave_device_config.yaml

logger:
  default: warning
  #default: debug
  logs:
    homeassistant.components.device_tracker: debug
#    homeassistant.components.device_tracker.mqtt: debug
#    custom_components.telegram_webhooks: debug
#    custom_components.grafana_webhooks: debug
#    homeassistant.components.http: debug
#    homeassistant.components.shell_command: debug

device_tracker: !include device_trackers.yaml

notify: !include notify.yaml

media_player: !include media_players.yaml

sensor: !include_dir_merge_list sensors

zone: !include zones.yaml

automation: !include_dir_list automation

group: !include groups.yaml

input_boolean: !include input_boolean.yaml

input_select: !include input_select.yaml

shell_command: !include shell_command.yaml

script: !include_dir_named scripts


###########################################

weblink:
  entities:
    - name: Musica
      url: http://cubo.home:6680/musicbox_webclient
    - name: Grafana
      url: http://pi.csgalileo.org/grafana/
    - name: Cloud
      url: http://pi.csgalileo.org/cloud/

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

camera:
  - platform: foscam
    ip: 192.168.2.14
    port: 80
    username: foscam
    password: !secret foscam_c1
    # rtsp url: rtsp://foscam:foscam1@192.168.2.21:554/11
    # rtsp mcast: rtsp://192.168.2.21:554/11
#  - platform: generic
#    name: 'Bianca'
#    still_image_url: http://192.168.2.12:80/cgi-bin/anv/images_cgi?channel=0&user=admin&pwd=admin
#    # sito del costruttore: http://www.szsinocam.net/ (non il .com) 
#    # model: szsinocam SN-IPC-5029CSW
#    # rtsp url: rtsp://192.168.2.12:554/ucast/11
#  - platform: onvif
#    host: 192.168.2.29
#    username: admin
#    password: admin
#    port: 1018
#  - platform: ffmpeg
#    input: rtsp://192.168.2.29:554/11
#    name: cancello
  - platform: mjpeg
    name: cancello
    still_image_url: http://192.168.2.35:8080/RJoxdaN1AkIpD0h8h7NESDhjYKinEA/jpeg/VqgnnhxiIp/pmC4mZ4g5U/s.jpg
    mjpeg_url: http://192.168.2.35:8080/RJoxdaN1AkIpD0h8h7NESDhjYKinEA/mjpeg/VqgnnhxiIp/pmC4mZ4g5U




#graphite:
#  host: 127.0.0.1
#  port: 2003

influxdb:
  host: 127.0.0.1
  port: 8086
  include:
    entities:
       - sensor.contatore_power_2
       - sensor.contatore_power_3
       - sensor.frigorifero_power
       - sensor.lavastoviglie_power
       - sensor.lavatrice_power
       - sensor.multi_soggiorno_luminance
       - sensor.multi_soggiorno_relative_humidity
       - sensor.multi_soggiorno_temperature
       - sensor.multi_portico_luminance
       - sensor.multi_portico_temperature
       - sensor.multi_portico_seismic_intensity
       - sensor.multi_camere_luminance
       - sensor.multi_camere_temperature
       - sensor.multi_camere_seismic_intensity
       - sun.sun
       - sensor.speedtest_download
       - sensor.speedtest_upload
       - sensor.speedtest_ping
       - sensor.yweather_temperature_max
       - sensor.yweather_temperature_min
       - sensor.yweather_condition



telegram_bot:
  platform: webhooks
  api_key: !secret telegram_token
  trusted_networks:
    - 149.154.167.197/32
    - 149.154.167.198/31
    - 149.154.167.200/29
    - 149.154.167.208/28
    - 149.154.167.224/29
    - 149.154.167.232/31
  allowed_chat_ids:
    - 73496590
    - 84015820
    #- -209766105


#microsoft_face:
#  api_key: !secret microsoft_api


grafana_webhooks:

panel_iframe:
  music:
    title: 'Music'
    url: !secret music_url
  consumi:
    title: 'Consumi'
    url: https://scipio.csgalileo.org/grafana/dashboard/db/consumi?orgId=2
  sensori:
    title: 'Sensori'
    url: https://scipio.csgalileo.org/grafana/dashboard/db/sensori?orgId=2

tts:
  - platform: google
    language: 'en'
  - platform: picotts
    language: 'en-US'
    #language: 'it_I'

switch:
  - platform: broadlink
    host: 192.168.2.28
    mac: '34:ea:34:f4:26:a1'
    timeout: 15
    switches:
      tv_lg_power:
        friendly_name: "LG Tv Power"
        command_on: 'JgBYAAABKZITEhQRFDYTEhQRExEUERQRFDYSNxMSFDYUNhQ1EzcTNxMSFBETERQ2FBEUERQRFBETNhQ2EzcUEBQ2EzcRORM2EQAFKgABKUkUAAxZAAEqSBQADQU='
        command_off: 'JgBYAAABKZITEhQRFDYTEhQRExEUERQRFDYSNxMSFDYUNhQ1EzcTNxMSFBETERQ2FBEUERQRFBETNhQ2EzcUEBQ2EzcRORM2EQAFKgABKUkUAAxZAAEqSBQADQU='
      tv_lg_mute:
        friendly_name: "LG Tv Mute"
        command_on: 'JgBgAAABKpITEhQRFDUTEhQRFBETEhQRFDUSOBEUFDYROBM3ETkTNhM3ERQUERQ1ExIUERQRFBEUERM2FDYRFBQ2EzYUNhQ2EwAFJwABKkgTAAxZAAEpSRQADFkAASlJFAANBQAAAAAAAAAA'
        #command_off: 'JgBgAAABKpITEhQRFDUTEhQRFBETEhQRFDUSOBEUFDYROBM3ETkTNhM3ERQUERQ1ExIUERQRFBEUERM2FDYRFBQ2EzYUNhQ2EwAFJwABKkgTAAxZAAEpSRQADFkAASlJFAANBQAAAAAAAAAA'


conversation:
  intents:
    HassShoppingListAddItem:
      - Add {item} to my shopping list

shopping_list:

map:

python_script:
