hide_entity: true
trigger:
  platform: state
  entity_id: input_boolean.face_add
  from: 'off'
  to: 'on'
action:
  - service: microsoft_face.face_person
    data:
      group: famiglia
      name: 'scipio'
      camera_entity: camera.foscam_camera


