alias: 'telegram bot'
hide_entity: true
trigger:
  platform: event
  event_type: telegram.command
  event_data:
    command: '/ping'
action:
  - service: notify.telegram
    data:
      message: pong 

