alias: 'telegram bot start'
hide_entity: true
trigger:
  platform: state
  entity_id: telegram_webhooks.command
  to: '/start'
action:
  - service: notify.telegram
    data:
      message: 'commands'
      data:
        keyboard:
          - '/ping, /alarm'
          - '/siren'


