alias: 'telegram bot'
hide_entity: true
trigger:
  platform: event
  event_type: telegram.command
  event_data:
    command: '/ping'
action:
  - service: notify.telegram
    data:
      message: "pong"
  - service: tts.google_say 
    data:
      entity_id: media_player.gstreamer
      message: "this is a test pong reply"

