# see https://community.home-assistant.io/t/passing-dynamic-info-to-shell-command/4212/3
alias: 'telegram youtube'
hide_entity: true
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/play'
action:
  - service: notify.telegram
    data_template:
      message: 'playing ...'
#  - service: notify.telegram
#    data_template:
#      message: '3 playing {{ trigger.event.data["args"] }}'
  - service: shell_command.youtube_play
    data_template:
      #text: 'https://www.youtube.com/watch?v=_Lv6LkAmFTU'
      text: '{{trigger.event.data["args"][0]}}'

