alias: 'telegram bot start'
hide_entity: true
trigger:
  platform: event
  event_type: telegram.command
  event_data:
    command: '/start'
action:
  - service: notify.telegram
    data:
      message: 'commands'
      data:
        keyboard:
          - '/ping, /alarm_off'
          - '/siren'


