alias: 'telegram youtube BOT'
hide_entity: true
trigger:
  platform: event
  event_type: telegram_text
action:
  - service: shell_command.youtube_play
    data_template:
      text: "{{ trigger.event.data.text }}"

