alias: 'wifi disarma automaticamente allarme'
hide_entity: true
trigger:
  platform: state
  entity_id: group.famiglia
  from: 'not_home'
  to: 'home'
  for:
    seconds: 5
    minutes: 0
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.allarme_armato
